version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/docker-react
    ports:
      - 3000:3000
    image: app:react
    container_name: docker-react
    command: npm start